spring:
  data:
    cassandra:
      keyspace-name: main
      username: gumtIaUZwpscEkWrvaQIXanL
      password: dnWsGyL_.4Y6B8,4IGhj4ia,KMW3ZxGZ,-0.kD5ldsw8LvE3aKp9+rw0AK2ZFvzadH.U648QSqll3ZD.6Pc,6.tK_pz6g395pryZzX-uwUS0MUSYPRoxEdxL,tuPDBmq
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: bookopedia-secure-bundle.zip

astra.db:
  id: d22e3795-a546-4719-b6e7-31db7cb7e0cd-1
  region: ap-southeast-1
  keyspace: main
  application.token: AstraCS:gumtIaUZwpscEkWrvaQIXanL:88bda2ffa82fa00b20f0043885104429a7ad8c48fa4e8c8c4fd19422693967da
